### ISSUE TITLE
Map_Anapolictic freezes clients when spawning in

### ISSUE THREAD

**Issue by Kenkoman** [ClayHanson/BlocklandRebuilt-IssueBoard#362] opened 2023-07-29 21:50 UTC
### Bug Description
The map [Anapolictic](https://bl.kenko.dev/Add-ons/Retail/Map/Map_Anapolictic.zip) hangs clients on spawn. A server can load the map fine, but any client trying to spawn into it will have their games freeze just before they spawn.

### Metadata:
 - Game Version: `v1.4-rev1880`

**Comment by ClayHanson** [comment] 2023-08-01 13:59
I cannot replicate this issue

**Comment by Kenkoman** [comment] 2023-08-01 15:15
On a completely clean (other than this map) install of `v1.5-rev1904` I can still replicate this

**Comment by ClayHanson** [comment] 2023-08-16 13:44
This seems to be an issue with release build optimizations. I have addressed the issue.

**Comment by consoleSkunk** [comment] 2023-09-14 01:27
Confirmed fixed in `v1.9`

**Closed as completed** 2023-09-21 18:57 UTC
Labels: Maps, Bug, Addressed in Next Version
