### ISSUE TITLE
Color codes misbehaving in bottomprint

### ISSUE THREAD

**Issue by maxymax13** [ClayHanson/BlocklandRebuilt-IssueBoard#289] opened 2023-07-16 23:39 UTC
### Bug Description
\c8 is becoming a weird mint color instead of black

### Screenshots
v1.0:
![image](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/38844529/2df4d8ca-e08e-48c1-9e92-03731b135987)
v20:
![image](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/38844529/1a439905-a09b-4be2-95e9-3c04c139e1c4)

### Metadata:
 - Game Version: `v1.0`

### Additional context
Didn't happen in older rebuilt versions IIRC?

**Comment by maxymax13** [comment] 2023-07-17 00:05
![image](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/38844529/d509a300-a08b-449f-8e8f-f6e1975b0628)

**Comment by consoleSkunk** [comment] 2023-07-17 00:21
Font colors 8 (`94 0 105 0`) and 9 (`121 0 128 0`) have an alpha color set to 0, i.e. fully transparent.

**Comment by consoleSkunk** [comment] 2023-09-21 19:19
![Screenshot_2023-09-21_13-19-06](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/50500602/6d248ab6-611f-4cc5-96bb-5ce30558f121)

Cannot reproduce this in `v1.9`, closing.

**Closed as completed by consoleSkunk** 2023-09-21 19:19 UTC
Labels: Bug
