### ISSUE TITLE
Slayer uniform editor / avatar editor crashes game

### ISSUE THREAD

**Issue by Cowtastic141** [ClayHanson/BlocklandRebuilt-IssueBoard#299] opened 2023-07-17 07:46 UTC
### Bug Description
When trying to edit a team uniform, the game crashes to desktop on opening the UI.

### To Reproduce
Optionally, provide us with instructions/explanation on how we can reproduce this problem.
1. Make a Slayer TDM minigame
2. Add a team, set uniform to Custom
3. Click on the Uniform button
4. Your game will crash

### Metadata:
 - Game Version: `v1.0`

**Comment by ClayHanson** [comment] 2023-07-17 16:02
I cannot reproduce this crash in v1.1; Marking as 'addressed'.

**Comment by maxymax13** [comment] 2023-07-18 15:42
![image](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/38844529/2607c897-94d1-479c-b910-d1496e692591)
works in v1.1

**Closed as completed** 2023-07-21 15:32 UTC
Labels: Bug
